---
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-ca
  namespace: kube-system
  labels:
    k8s-app: es-ca
    kubernetes.io/cluster-service: "true"
data:
  ca.pem: |-
    -----BEGIN CERTIFICATE-----
    MIIDVjCCAj6gAwIBAgIRAIzAcHJvBPWMA4M3TllvmQYwDQYJKoZIhvcNAQELBQAw
    NTEWMBQGA1UECxMNZWxhc3RpY3NlYXJjaDEbMBkGA1UEAxMSZWxhc3RpY3NlYXJj
    aC1odHRwMB4XDTIzMDIyNTEzMzU1MloXDTI0MDIyNTEzNDU1MlowNTEWMBQGA1UE
    CxMNZWxhc3RpY3NlYXJjaDEbMBkGA1UEAxMSZWxhc3RpY3NlYXJjaC1odHRwMIIB
    IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvVojUXKnvftTPntSEZu9+fPN
    YzMc8SbOgMqbWiOVRnIXuF3nKuqu6ajlXXD/cVvyagqiznbkN+3/R98GBr8KjV66
    0WYYt5TiD7plrzsmQvKOTmkGu4l8YHmn5cuNhsYXUFiwYIylRGnyIvw165A5MpV6
    WolC5e+YFZzhn5UUVZ8w2LrG69WDhKXxiyghhe9LmtFVXQmeYlfypl3Cz9VcCfE/
    2G5JmD9m/JDt3rgXxHn6Xq0C+NLXKDYEOsQB3zyl6xsQM+2HL2BpVoTiC4ZFGAV1
    EjRyBVTDN3ZtIVUHG8gFtsDKQKV1VFnhcpe3CmEzn0foDnWlj0eE95eXqzpX9wID
    AQABo2EwXzAOBgNVHQ8BAf8EBAMCAoQwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsG
    AQUFBwMCMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFO7hn0hfFJyaYdGrO2Gb
    SUmMFwPCMA0GCSqGSIb3DQEBCwUAA4IBAQB6xgBVtg32CvgtNkyxETz/pW4ktpEq
    dZlaqvC4hA7aJqR6G4ulVEI9v3pVQMSNOmviCVPCods+GLGskAH/Gx2S1FEiWVQC
    B5ysPxXeUpuy4/8CQ7PZirNgwQocZWQqmBWP09xrk8nc6SEI34csp7Kw7+QO+hlx
    GWLLPO9sb5TPLb8+otWMR5joApAxCi/OIAT7see2OrD9+zHb+5W/j6weOEATGsHf
    nDRkdwpMgWnj7i03YeycfXnx2zFoDdxIhAMLgTDGNsbAlvqdjtfoHER8paiS78bi
    AOxG6olu/LsMNARMEvMubpETsAxR2S5AgxdkfNNZHzo59HZWsLlU8BiB
    -----END CERTIFICATE-----
